apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxprojectausingjenkins
  labels:
    color: blue
    app: erp
spec:
  replicas: 3
  template:
    metadata:
      name: nginxpodawithjenkins
      labels:
        app: erp
    spec:
     containers:
       - name: deploymentcontainerprojectajenkins
         image: nginx
  selector:
    matchLabels:
      app: erp	
      
---
apiVersion: v1
kind : Service
metadata:
  name: jenkinsprojectawithjenkins
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginxold
    
