apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-12T14:59:10Z"
  generation: 1
  labels:
    app: erp
    color: blue
  name: nginxdeploymentusingjenkins
  namespace: default
  resourceVersion: "1227281"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nginxdeploymentusingjenkins
  uid: 1605125c-328a-4d5d-97e2-610708feb18e
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: erp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: erp
      name: deploymentpodinyamlusingjenkins
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: deploymentcontainerinyamlusingjenkins
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-04-12T14:59:13Z"
    lastUpdateTime: "2020-04-12T14:59:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-12T14:59:10Z"
    lastUpdateTime: "2020-04-12T14:59:13Z"
    message: ReplicaSet "nginxdeploymentusingjenkins-564446b866" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
